# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Rent.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setFixedSize(400, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(140, 390, 100, 30))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setAutoRepeatDelay(300)
        self.pushButton.setObjectName("pushButton")
        self.typeCombo = QtWidgets.QComboBox(self.centralwidget)
        self.typeCombo.setEnabled(False)
        self.typeCombo.setGeometry(QtCore.QRect(200, 310, 110, 30))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.typeCombo.setFont(font)
        self.typeCombo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.typeCombo.setAutoFillBackground(False)
        self.typeCombo.setDuplicatesEnabled(False)
        self.typeCombo.setObjectName("typeCombo")
        self.typeCombo.addItem("")
        self.areaLabel = QtWidgets.QLabel(self.centralwidget)
        self.areaLabel.setEnabled(True)
        self.areaLabel.setGeometry(QtCore.QRect(90, 70, 90, 30))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.areaLabel.setFont(font)
        self.areaLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.areaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.areaLabel.setObjectName("areaLabel")
        self.roomsLabel = QtWidgets.QLabel(self.centralwidget)
        self.roomsLabel.setEnabled(True)
        self.roomsLabel.setGeometry(QtCore.QRect(90, 110, 90, 30))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.roomsLabel.setFont(font)
        self.roomsLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.roomsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.roomsLabel.setObjectName("roomsLabel")
        self.bathroomsLabel = QtWidgets.QLabel(self.centralwidget)
        self.bathroomsLabel.setEnabled(True)
        self.bathroomsLabel.setGeometry(QtCore.QRect(90, 190, 90, 30))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.bathroomsLabel.setFont(font)
        self.bathroomsLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bathroomsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bathroomsLabel.setObjectName("bathroomsLabel")
        self.dinningLabel = QtWidgets.QLabel(self.centralwidget)
        self.dinningLabel.setEnabled(True)
        self.dinningLabel.setGeometry(QtCore.QRect(90, 150, 90, 30))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.dinningLabel.setFont(font)
        self.dinningLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dinningLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dinningLabel.setObjectName("dinningLabel")
        self.floorsLabel = QtWidgets.QLabel(self.centralwidget)
        self.floorsLabel.setEnabled(True)
        self.floorsLabel.setGeometry(QtCore.QRect(90, 230, 90, 30))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.floorsLabel.setFont(font)
        self.floorsLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.floorsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.floorsLabel.setObjectName("floorsLabel")
        self.totalFloorsLabel = QtWidgets.QLabel(self.centralwidget)
        self.totalFloorsLabel.setEnabled(True)
        self.totalFloorsLabel.setGeometry(QtCore.QRect(90, 270, 90, 30))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.totalFloorsLabel.setFont(font)
        self.totalFloorsLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.totalFloorsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.totalFloorsLabel.setObjectName("totalFloorsLabel")
        self.typeLabel = QtWidgets.QLabel(self.centralwidget)
        self.typeLabel.setEnabled(True)
        self.typeLabel.setGeometry(QtCore.QRect(90, 310, 90, 30))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.typeLabel.setFont(font)
        self.typeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.typeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.typeLabel.setObjectName("typeLabel")
        self.districtLabel = QtWidgets.QLabel(self.centralwidget)
        self.districtLabel.setEnabled(True)
        self.districtLabel.setGeometry(QtCore.QRect(90, 350, 90, 30))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.districtLabel.setFont(font)
        self.districtLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.districtLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.districtLabel.setObjectName("districtLabel")
        self.districtCombo = QtWidgets.QComboBox(self.centralwidget)
        self.districtCombo.setEnabled(False)
        self.districtCombo.setGeometry(QtCore.QRect(200, 350, 110, 30))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.districtCombo.setFont(font)
        self.districtCombo.setObjectName("districtCombo")
        self.districtCombo.addItem("")
        self.districtCombo.addItem("")
        self.districtCombo.addItem("")
        self.districtCombo.addItem("")
        self.districtCombo.addItem("")
        self.districtCombo.addItem("")
        self.districtCombo.addItem("")
        self.districtCombo.addItem("")
        self.districtCombo.addItem("")
        self.totalFloorsLine = QtWidgets.QLineEdit(self.centralwidget)
        self.totalFloorsLine.setEnabled(False)
        self.totalFloorsLine.setGeometry(QtCore.QRect(200, 270, 110, 30))
        self.totalFloorsLine.setAlignment(QtCore.Qt.AlignCenter)
        self.totalFloorsLine.setObjectName("totalFloorsLine")
        self.roomsLine = QtWidgets.QLineEdit(self.centralwidget)
        self.roomsLine.setEnabled(True)
        self.roomsLine.setGeometry(QtCore.QRect(210, 110, 90, 30))
        self.roomsLine.setAlignment(QtCore.Qt.AlignCenter)
        self.roomsLine.setObjectName("roomsLine")
        self.dinningLine = QtWidgets.QLineEdit(self.centralwidget)
        self.dinningLine.setEnabled(True)
        self.dinningLine.setGeometry(QtCore.QRect(210, 150, 90, 30))
        self.dinningLine.setAlignment(QtCore.Qt.AlignCenter)
        self.dinningLine.setObjectName("dinningLine")
        self.bathroomsLine = QtWidgets.QLineEdit(self.centralwidget)
        self.bathroomsLine.setEnabled(True)
        self.bathroomsLine.setGeometry(QtCore.QRect(210, 190, 90, 30))
        self.bathroomsLine.setAlignment(QtCore.Qt.AlignCenter)
        self.bathroomsLine.setObjectName("bathroomsLine")
        self.areaLine = QtWidgets.QLineEdit(self.centralwidget)
        self.areaLine.setEnabled(True)
        self.areaLine.setGeometry(QtCore.QRect(210, 70, 90, 30))
        self.areaLine.setAlignment(QtCore.Qt.AlignCenter)
        self.areaLine.setObjectName("areaLine")
        self.floorsLine = QtWidgets.QLineEdit(self.centralwidget)
        self.floorsLine.setEnabled(False)
        self.floorsLine.setGeometry(QtCore.QRect(200, 230, 110, 30))
        self.floorsLine.setAlignment(QtCore.Qt.AlignCenter)
        self.floorsLine.setObjectName("floorsLine")
        self.rentLabel = QtWidgets.QLabel(self.centralwidget)
        self.rentLabel.setGeometry(QtCore.QRect(90, 450, 220, 30))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.rentLabel.setFont(font)
        self.rentLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rentLabel.setObjectName("rentLabel")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(150, 490, 80, 30))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.resultLabel.setFont(font)
        self.resultLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.resultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultLabel.setObjectName("resultLabel")
        self.useLabel = QtWidgets.QLabel(self.centralwidget)
        self.useLabel.setEnabled(True)
        self.useLabel.setGeometry(QtCore.QRect(90, 30, 90, 30))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.useLabel.setFont(font)
        self.useLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.useLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.useLabel.setObjectName("useLabel")
        self.useLine = QtWidgets.QLineEdit(self.centralwidget)
        self.useLine.setGeometry(QtCore.QRect(210, 30, 90, 30))
        self.useLine.setAlignment(QtCore.Qt.AlignCenter)
        self.useLine.setObjectName("useLine")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "預測租金"))
        self.typeCombo.setItemText(0, _translate("MainWindow", "-"))
        self.areaLabel.setText(_translate("MainWindow", "面積(坪)"))
        self.roomsLabel.setText(_translate("MainWindow", "房間數"))
        self.bathroomsLabel.setText(_translate("MainWindow", "衛浴數"))
        self.dinningLabel.setText(_translate("MainWindow", "廳數"))
        self.floorsLabel.setText(_translate("MainWindow", "樓層數"))
        self.totalFloorsLabel.setText(_translate("MainWindow", "總樓層數"))
        self.typeLabel.setText(_translate("MainWindow", "類型"))
        self.districtLabel.setText(_translate("MainWindow", "區域"))
        self.districtCombo.setItemText(0, _translate("MainWindow", "-"))
        self.districtCombo.setItemText(1, _translate("MainWindow", "中區"))
        self.districtCombo.setItemText(2, _translate("MainWindow", "北區"))
        self.districtCombo.setItemText(3, _translate("MainWindow", "南區"))
        self.districtCombo.setItemText(4, _translate("MainWindow", "東區"))
        self.districtCombo.setItemText(5, _translate("MainWindow", "西區"))
        self.districtCombo.setItemText(6, _translate("MainWindow", "北屯區"))
        self.districtCombo.setItemText(7, _translate("MainWindow", "南屯區"))
        self.districtCombo.setItemText(8, _translate("MainWindow", "西屯區"))
        self.totalFloorsLine.setPlaceholderText(_translate("MainWindow", "不可小於樓層數"))
        self.floorsLine.setPlaceholderText(_translate("MainWindow", "不可大於總樓層數"))
        self.rentLabel.setText(_translate("MainWindow", "估計月租金建議定價為"))
        self.resultLabel.setText(_translate("MainWindow", ">_<"))
        self.useLabel.setText(_translate("MainWindow", "用途"))
        self.useLine.setPlaceholderText(_translate("MainWindow", "居住or商業"))

